{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2019-9948",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://bugs.python.org/issue35907",
                "refsource": "MISC",
                "name": "https://bugs.python.org/issue35907"
            },
            {
                "url": "https://github.com/python/cpython/pull/11842",
                "refsource": "MISC",
                "name": "https://github.com/python/cpython/pull/11842"
            },
            {
                "refsource": "BID",
                "name": "107549",
                "url": "http://www.securityfocus.com/bid/107549"
            },
            {
                "refsource": "CONFIRM",
                "name": "https://security.netapp.com/advisory/ntap-20190404-0004/",
                "url": "https://security.netapp.com/advisory/ntap-20190404-0004/"
            },
            {
                "refsource": "SUSE",
                "name": "openSUSE-SU-2019:1273",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html"
            },
            {
                "refsource": "SUSE",
                "name": "openSUSE-SU-2019:1580",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00050.html"
            },
            {
                "refsource": "MLIST",
                "name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1834-1] python2.7 security update",
                "url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html"
            },
            {
                "refsource": "REDHAT",
                "name": "RHSA-2019:1700",
                "url": "https://access.redhat.com/errata/RHSA-2019:1700"
            },
            {
                "refsource": "MLIST",
                "name": "[debian-lts-announce] 20190711 [SECURITY] [DLA 1852-1] python3.4 security update",
                "url": "https://lists.debian.org/debian-lts-announce/2019/07/msg00011.html"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-9bfb4a3e4b",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KRYFIMISZ47NTAU3XWZUOFB7CYL62KES/"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-60a1defcd1",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HQEQLXLOCR3SNM3AA5RRYJFQ5AZBYJ4L/"
            },
            {
                "refsource": "REDHAT",
                "name": "RHSA-2019:2030",
                "url": "https://access.redhat.com/errata/RHSA-2019:2030"
            },
            {
                "refsource": "UBUNTU",
                "name": "USN-4127-2",
                "url": "https://usn.ubuntu.com/4127-2/"
            },
            {
                "refsource": "UBUNTU",
                "name": "USN-4127-1",
                "url": "https://usn.ubuntu.com/4127-1/"
            },
            {
                "refsource": "BUGTRAQ",
                "name": "20191021 [slackware-security] python (SSA:2019-293-01)",
                "url": "https://seclists.org/bugtraq/2019/Oct/29"
            },
            {
                "refsource": "MISC",
                "name": "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html",
                "url": "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html"
            },
            {
                "refsource": "REDHAT",
                "name": "RHSA-2019:3335",
                "url": "https://access.redhat.com/errata/RHSA-2019:3335"
            },
            {
                "refsource": "REDHAT",
                "name": "RHSA-2019:3520",
                "url": "https://access.redhat.com/errata/RHSA-2019:3520"
            },
            {
                "refsource": "GENTOO",
                "name": "GLSA-202003-26",
                "url": "https://security.gentoo.org/glsa/202003-26"
            }
        ]
    }
}