{
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
        "ID": "CVE-2020-10735",
        "ASSIGNER": "secalert@redhat.com",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "n/a",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "python",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "python 3.7"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "DoS"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "refsource": "MISC",
                "name": "https://access.redhat.com/security/cve/CVE-2020-10735",
                "url": "https://access.redhat.com/security/cve/CVE-2020-10735"
            },
            {
                "refsource": "MISC",
                "name": "https://github.com/python/cpython/issues/95778",
                "url": "https://github.com/python/cpython/issues/95778"
            },
            {
                "refsource": "MISC",
                "name": "https://docs.google.com/document/d/1KjuF_aXlzPUxTK4BMgezGJ2Pn7uevfX7g0_mvgHlL7Y",
                "url": "https://docs.google.com/document/d/1KjuF_aXlzPUxTK4BMgezGJ2Pn7uevfX7g0_mvgHlL7Y"
            },
            {
                "refsource": "MISC",
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1834423",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1834423"
            }
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "A flaw was found in python. In algorithms with quadratic time complexity using non-binary bases, when using int(\"text\"), a system could take 50ms to parse an int string with 100,000 digits and 5s for 1,000,000 digits (float, decimal, int.from_bytes(), and int() for binary bases 2, 4, 8, 16, and 32 are not affected). The highest threat from this vulnerability is to system availability."
            }
        ]
    }
}