{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2019-18348",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "An issue was discovered in urllib2 in Python 2.x through 2.7.17 and urllib in Python 3.x through 3.8.0. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the host component of a URL) followed by an HTTP header. This is similar to the CVE-2019-9740 query string issue and the CVE-2019-9947 path string issue. (This is not exploitable when glibc has CVE-2016-10739 fixed.)"
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1727276",
                "refsource": "MISC",
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1727276"
            },
            {
                "url": "https://bugs.python.org/issue30458#msg347282",
                "refsource": "MISC",
                "name": "https://bugs.python.org/issue30458#msg347282"
            },
            {
                "refsource": "CONFIRM",
                "name": "https://security.netapp.com/advisory/ntap-20191107-0004/",
                "url": "https://security.netapp.com/advisory/ntap-20191107-0004/"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-b06ec6159b",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-d202cda4f8",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-57462fa10d",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/"
            },
            {
                "refsource": "UBUNTU",
                "name": "USN-4333-1",
                "url": "https://usn.ubuntu.com/4333-1/"
            },
            {
                "refsource": "UBUNTU",
                "name": "USN-4333-2",
                "url": "https://usn.ubuntu.com/4333-2/"
            },
            {
                "refsource": "SUSE",
                "name": "openSUSE-SU-2020:0696",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00041.html"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2020-8bdd3fd7a4",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UESGYI5XDAHJBATEZN3MHNDUBDH47AS6/"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2020-ea5bdbcc90",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A5NSAX4SC3V64PGZUPH7PRDLSON34Q5A/"
            },
            {
                "refsource": "MLIST",
                "name": "[debian-lts-announce] 20200715 [SECURITY] [DLA 2280-1] python3.5 security update",
                "url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html"
            }
        ]
    }
}